config/routes.rb
SocialStreamDitUpmEs::Application.routes.draw do
  match "/community" => "frontpage#community", :as => :community
  match "/started"   => "frontpage#started",   :as => :started

  match "/wp-content/*dir" => redirect { |env, req| "http://blog-social-stream.dit.upm.es/wp-content/#{ env[:dir] }.#{ env[:format] }" }
  match "/20*dir" => redirect{ |env, req| "http://blog-social-stream.dit.upm.es/wp-content/#{ env[:dir] }" }

  root :to => 'frontpage#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/frontpage_controller.rb
class FrontpageController < ApplicationController
  def index
  end

  def community
  end

  def started
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/frontpage/_sidebar_rss.html.erb
<div id="text-4" class="widget widget_text">
  <a class="twitter-timeline" href="https://twitter.com/SocialStreamGem" data-widget-id="332442755815055361">Social Stream's Twitter</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</div>

app/views/frontpage/community.html.erb
<section id="comunity" class="row">
  <div class="websites">
    <div class="comunity">
      <h2>
        Google groups
        <img src="assets/logos/googlegroups-saturation.png" href="https://groups.google.com/forum/?fromgroups#!forum/social-stream" target="_blank" class="hidden-phone">
      </h2>
      <div class="content">
        <p>
          The main&nbsp;
          <a href="http://groups.google.com/group/social-stream" target="_blank">
            Social Stream group
          </a>
          &nbsp;is a great place to discuss issues and learn about how to get the most out of Social-Stream.
        </p>
        <form action="http://groups.google.com/group/social-stream/boxsubscribe">
          Email:&nbsp;
          <input type="text" name="email">&nbsp;<input class="btn btn-primary" type="submit" name="sub" value=" Subscribe to Social Stream group ">
        </form>
      </div>
      
    </div>
    <div class="comunity">
      <h2>
        StackOverflow
        <img src="assets/logos/stackoverflow-saturation.png" href="http://stackoverflow.com/questions/tagged/social-stream" target="_blank" class="hidden-phone">
      </h2>
      <div class="content">
        
        <p>
          <a href="http://stackoverflow.com/">
            StackOverflow
          </a> 
          is a awesome forum to get technical help in any fields. The 
          <a href="http://stackoverflow.com/questions/tagged/social-stream">
            social-stream tag in StackOverflow 
          </a>
          tracks questions about Social Stream.
        </p>
      </div>
      
    </div>
    <div class="comunity">
      <h2>
        GitHub
        <img src="assets/logos/github.png" href="https://github.com/ging/social_stream" target="_blank" class="hidden-phone">
      </h2>
      <div class="content">
        <p>
          Social Stream’s development takes place at 
          <a title="Social Stream's Github repository" href="https://github.com/ging/social_stream" target="_blank">
            Github
          </a>
          There you will find the issues tracker, wiki pages and pull requests.
        </p>
      </div>
    </div>
    <div class="comunity">
      <h2>
        Irc
        <img src="assets/logos/freenode-saturation.png" href="http://freenode.net/" target="_blank" class="hidden-phone">
      </h2>
      <div class="content">
        <p>
        We are usually connected to IRC at <a href="irc://irc.freenode.net/#socialstream">#socialstream room in Freenode</a>. Come and chat with us in real time!
        </p>
      </div>
    </div>
  </div>
  <div class="sidebar-rss">
    <%= render partial: "sidebar_rss" %>
  </div>  
</section> 

app/views/frontpage/index.html.erb
<div id="home">
  <section id="jms-slideshow" class="jms-slideshow row">
    <div class="step" data-color="color-1">
      <div class="jms-content">
        <h3>Build social network websites</h3>
        <p>Social Stream is a <a href="http://en.wikipedia.org/wiki/Free_and_open-source_software">FLOSS</a> framework packaged as a <a href="http://rubyonrails.org/">Ruby on Rails</a> gem. It lets you develop distributed social networks websites rapidly and flexibly
      </div>
      <img src="/assets/logo.png" />
    </div>
    <div class="step" data-color="color-2" data-y="500" data-scale="0.4" data-rotate-x="30">
      <div class="jms-content">
        <h3>Modular and flexible</h3>
        <p>Use only the components you need for your case. Customize appareance, functionality or create your own components</p>
        
      </div>
      <img src="/assets/paraque.png" />
    </div>
    <div class="step" data-color="color-3" data-x="2000" data-z="3000" data-rotate="170">
      <div class="jms-content">
        <h3>For Rails developers</h3>
        <p>Enjoy a <%= link_to "community of practitioners", community_path %> that support its quality</p>
        
      </div>
      <img src="/assets/developer-1.png" />
    </div>
    <div class="step" data-color="color-4" data-x="3000">
      <div class="jms-content">
        <h3>Start now!</h3>
        <p>Create you own web application and start the customization in <%= link_to "a few minutes", started_path %>!</p>
        
      </div>
      <img src="/assets/now.jpg" />
    </div>
  </section>
        
  <h1>Built with Social Stream</h1>
  <div id="myCarousel" class="carousel slide row">
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <!-- Carousel items -->
    <div class="carousel-inner">
      <div class="active item">
        <div class="thumb-buid-ss">
          <img src="/assets/vish.jpg">
        </div>
        <div class="description">
          <h2>
            ViSH
          </h2>
          <p>
            ViSH is a social network for scientists, teachers and pupils. It contains the infrastructure to build, share and participate in virtual excursions.
          </p>
          <a href="http://www.vishub.org/" class="btn btn-secundary">
            Visit this website
          </a>
        </div>
      </div>
      <div class="item">
        <div class="thumb-buid-ss">
          <img src="/assets/adviseonly.png">
        </div>
        <div class="description">
          <h2>
            advise only
          </h2>
          <p>
            The Advise Only Community is the Web 2.0 personal finance revolution, a place where users can share their investment portfolios.
          </p>
          <a href="https://www.adviseonly.com/" class="btn btn-secundary">
            Visit this website
          </a>
        </div>
      </div>
      <div class="item">
        <div class="thumb-buid-ss">
          <img src="/assets/placedonia.png">
        </div>
        <div class="description">
          <h2>
            placedonia
          </h2>
          <p>
            Placedonia is a places-oriented social network where users can save the places they like. They can also review comments on places, both from strangers and from their own contacts.
          </p>
          <a href="http://m-places.dit.upm.es/" class="btn btn-secundary">
            Visit this website
          </a>
        </div>
      </div>
    </div>
    <!-- Carousel nav -->
    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
  </div>




      <script type="text/javascript">
        $(function() {
        
          $( '#jms-slideshow' ).jmslideshow();
          
        });
      </script>

</div>

app/views/frontpage/started.html.erb
<div id="start">
  <div class="start-menu bs-docs-sidebar affix">
    <ul class="nav nav-list bs-docs-sidenav affix-top">
      <li><a href="#rails"><i class="icon-chevron-right"></i> 1. Get Started with Rails</a></li>
      <li><a href="#components"><i class="icon-chevron-right"></i> 2. Social Stream components</a></li>
      <li><a href="#install"><i class="icon-chevron-right"></i> 3. Install Social Stream</a></li>
      <li><a href="#customize"><i class="icon-chevron-right"></i> 4. Customize your application</a></li>
      <li><a href="#more"><i class="icon-chevron-right"></i> 5. More</a></li>
    </ul>
    <a class="down-submenu">
      <i class="icon-chevron-down"></i>
    </a>
  </div>

  <div class="content">
    <section id="rails" class="row get-started-with-rails">
      <header>
        <h1>
          1
        </h1>
        <h2>
          Get Started with Rails
        </h2>
      </header>
        
      <p>Social Stream is an engine for <a href="http://rubyonrails.org/">Ruby on Rails</a>, the popular web development framework. You need to know Rails before developing with Social Stream. There is a nice guide at <a href="http://guides.rubyonrails.org/getting_started.html">Getting Started with Rails</a> that you should read first.</p>

      <p>Once you have created your Rails application, you can add the Social Stream engine. Social Stream is quite modular, you can use only the functionalities you need in your application. Before installing Social Stream, you have to decide which components you will need in your new social network.</p>
    </section>

    <section id="components" class="row components">
      <div class="components">
        <header>
          <h1>
            2
          </h1>
          <h2>
            Social Stream's components
          </h2>  
        </header>
      </div>

      <p>Social Stream is splitted into components to provide developers with the precise functionality you need for their social network website. Every component is packaged as a <a href="http://rubygems.org/">Ruby Gem</a> which is the standard packaging in Ruby. Ruby on Rails itself is also packaged as a gem.</p>

      <p>Current available components in Social Stream are:</p>
    
      <ul class="nav nav-pills" id="components-tab">
        <li class="active"><a href="#base" data-toggle="tab">Base</a></li>
        <li><a href="#documents" data-toggle="tab">Documents</a></li>
        <li><a href="#events" data-toggle="tab">Events</a></li>
        <li><a href="#linkser" data-toggle="tab">Linkser</a></li>
        <li><a href="#presence" data-toggle="tab">Presence</a></li>
        <li><a href="#ostatus" data-toggle="tab">OStatus</a></li>
        <li><a href="#oauth2" data-toggle="tab">OAuth2 Server</a></li>
      </ul>
 
      <div class="tab-content">
        <div class="tab-pane active" id="base"> <blockquote>The <code>social_stream-base</code> gem provides applications with the core social network functionality. It supports users and groups, profile pages, activity streams, private messages and notifications, text posts and comments. Everything you need to start your social network.</blockquote></div>
        <div class="tab-pane" id="documents"><blockquote>The <code>social_stream-documents</code> gem adds the core support for file uploads. Besides, it adds some nice features to special files, such as image thumbnails, audio and video with an HTML5 player.</blockquote></div>
        <div class="tab-pane" id="events"><blockquote><code>social_stream-events</code> provides your social network with supports for scheduled events with a nice full-screen calendar.</blockquote></div>
        <div class="tab-pane" id="linkser"><blockquote><code>social_stream-linkser</code> adds advanced management of links to other webpages. These are quite popular in leisure social networks where people share a lot of Youtube videos, for instance.</blockquote></div>
        <div class="tab-pane" id="presence"><blockquote>The <code>social_stream-presence</code> gem provides your social network with chat and videoconference support.</blockquote></div>
        <div class="tab-pane" id="ostatus"><blockquote><code>social_stream-ostatus</code> lets your social network website federate with other social networks using the popular <a href="http://www.w3.org/community/ostatus/">OStatus</a> protocol.</blockquote></div>
        <div class="tab-pane" id="oauth2"><blockquote>The <code>social_stream-oauth2_server</code> gem turns your site into an <a href="http://oauth.net/2/">OAuth2</a> provider, letting third party applications to access authentication and protected services from your social network.</blockquote></div>
      </div>
    </section>

    <section id="install" class="row install-social-stream">
      <header>
        <h1>
          3
        </h1>
        <h2>
          Install Social Stream
        </h2>
      </header>
      <p>After deciding which Social Stream's components you will use for your application, you can install Social Stream, just adding the gems to your application's <code>Gemfile</code></p>

      <div class="row">
        <div class="step">
          <div class="option">
            <img src="/assets/step-line-double-top.png">
          </div>
        </div>

        <div class="mid-case">
          <p>If you are using the full Social Stream suite, add <code>social_stream</code> to your <code>Gemfile</code></p>

          <pre>
gem 'social_stream'
          </pre>
        </div>
      

        <div class="mid-case">
          <p>On the other hand, if you are using the <code>social_stream-documents</code> and <code>social_stream-events</code> components only, add:</p>

             <pre>
gem 'social_stream-documents'
gem 'social_stream-events'
            </pre>
        </div>
      </div>
  


      <div class="row">
        <div class="step">
          <div class="option">
            <img src="/assets/step-line-double-bottom.png">
          </div>
        </div>
        <div class="option">
          <div class="line-l">
          </div>
          <div class="line-r">
          </div>
        </div>
        <div class="full-case">
          Next, use <a href="http://gembundler.com/">Bundler</a>, the gem dependency manager to install all other gems required by your choice:
          <pre>
bundle
          </pre>
        </div>
      </div>


      <div class="row">
        <div class="step">
          <div class="option">
            <img src="/assets/step-line-double-top.png">
          </div>
        </div>
        <div class="mid-case">
          <p>The next step is running the generators for the gems. If you are installing the full Social Stream's suite:</p>

          <pre>
rails generate social_stream:install
          </pre>
        </div>
      
        <div class="mid-case">
          <p>In the case you are installing certain components, you must run the generator per each one of them:</p>

          <pre>
  rails generate social_stream:documents:install
  rails generate social_stream:events:install
          </pre>
        </div>
      </div>


      <div class="row">
        <div class="step">
          <div class="option">
            <img src="/assets/step-line-double-bottom.png">
          </div>
        </div>
        <div class="mid-full">
          Social Stream is not compatible with default mass attributes protection shipped with Rails 3.2.3, but uses the <a href="https://rubygems.org/gems/strong_parameters">strong_parameters gem</a> that will be the default in Rails 4. Set this in your <code>config/application.rb</code> before running the migration command:

          <pre>
config.active_record.whitelist_attributes = false
          </pre>
        </div>
      </div>

      <div class="row">
        <div class="step">
          <div class="option">
            <img src="/assets/step-line.png">
          </div>
        </div>
        <div class="mid-full">
          Now migrate your database:

          <pre>
rake db:migrate
          </pre>
        </div>
      </div>


      <div class="row">
        <div class="step">
          <div class="option">
            <img src="/assets/step-line.png">
          </div>
        </div>
        <div class="mid-full">
          Since Social Stream depends on <a href="https://github.com/plataformatec/devise">Devise</a>, make sure you follow its setup instructions. Specifically, make sure you set the default URL options for your environments at <code>config/environments/*.rb</code> with something like:

          <pre>
config.action_mailer.default_url_options = { :host => 'localhost:3000' }
          </pre>
        </div>
      </div>
    </section>


    <section id="customize" class="row">
      <header>
        <h1>
          4
        </h1>
        <h2>
          Customize your application
        </h2>
      </header>

      Now you have your own application up and running! The next step is customizing your application. Now you will learn how to quickly change its appareance. All the examples are demonstrated in the <a href="https://github.com/ging/social_stream-started">social_stream-started application</a>. You can download it and follow all the examples.

      <h3>Quickly change the branding of your social network</h3>

      <h4 id="change-color">Change the color using Bootstrap's variables</h4>
      Social Stream is built in the top of <a href="http://twitter.github.io/bootstrap/">Bootstrap</a>, the popular and powerful framework front-end framework. You can use Bootstrap's variables to customize your social network! For example, you can easily change the color of your social network. Just add the following to the top of <code>app/assets/stylesheets/social_stream.css.sass</code>
      <pre>

      </pre>

      <h4 id="change-logo">Change the logo</h4>
      All the assets (images, javascripts, stylesheets) in your application have the highest priority over the ones in Social Stream. You can easily change the social network logo placing an image at <code>app/assets/images/header-logo-index.png</code>, which will be sent to the server before <a href="https://github.com/ging/social_stream/blob/master/base/app/assets/images/header-logo-index.png">Social Stream's header-logo-index.png</a>

      <h3>Change the views</h3>
      <em>Where are the views?</em> you will probably ask. Social Stream is <a href="http://guides.rubyonrails.org/engines.html#what-are-engines">Rails Engine</a>. Everything (images, javascripts, css, views, models, controllers, etc.) is packaged within the gem, in an obscure place in your computer. But do not desperate! You still have full control on them and can change them in two ways, with Deface or overwriting them.

        <h4>Defacing views</h4>

        Using <a href="https://github.com/spree/deface">Spree's Deface</a> to change the views is the recomended way to go. Why? Because you will benefit from bug fixes and new features in new versions of Social Stream. If you just overwrite the views, these changes won't be propagated to your final application.

        <h4>Overwriting views</h4>

        The other option is completely overwrite the view. This makes change when the view is significantly different from the one in Social Stream. To achieve this, just place a view with the same path in your application. As in the <a href="#change-logo">case of the assets explained above</a>, Rails will pick your application's view before Social Stream's

      <h3>Customize models</h3>
      - decorators
      - overrite?
    </section>

    <section id="more" class="row">
      <header>
        <h1>
            5
        </h1>
        <h2>
          More
        </h2>
      </header>
      Need more? Try this:

      <ul>
        <li><a href="https://github.com/ging/social_stream/wiki/How-to-add-new-activity-objects">Adding new activity objects to the social network</a></li>
        <li>Social Stream's <a href="https://github.com/ging/social_stream/wiki/Social-Stream-Base-database-schema">base database schema</a> and <a href="https://github.com/ging/social_stream/wiki/Social-Stream-database-schema">full database schema</a></li>
    </section>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
  <title>Social Stream</title>
  <meta name="description" content="A framework for building distributed social network websites" />
  <meta name="keywords" content="social network framework, ruby on rails, social software, open source, ruby, rails, core, build, css3" />
  <meta name="Social-Stream" content="whit love for you" />
  <link rel="shortcut icon" href="/images/favicon.ico"> 
  <meta name="robots" content="index, follow"/>
  <%= stylesheet_link_tag    "application", media: 'all' %>
  <%= javascript_include_tag "application" %>

  <noscript>
    <style>
    .step {
      width: 100%;
      position: relative;
    }
    .step:not(.active) {
      opacity: 1;
      filter: alpha(opacity=99);
      -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(opacity=99)";
    }
    .step:not(.active) a.jms-link{
      opacity: 1;
      margin-top: 40px;
    }
    </style>
  </noscript>

  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-25541706-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript';
      ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(ga, s);
    })();

  </script>
</head>

<body>
  <header id="inner-header" class="clearfix">
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid nav-container">
          <nav role="navigation">
            <a class="brand" id="logo" href="/">
              <div class="logo">
              </div>
            </a>

            <button type="button" class="btn btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

            <div class="nav-collapse collapse">
              <ul class="nav">
                <li class="<%= current_page?(action: 'index') && 'active' %>">
                  <%= link_to "Home", root_path %>
                </li>
                <li class="">
                  <a href="http://blog-social-stream.dit.upm.es/">Blog</a>
                </li>
                <li class="">
                  <%= link_to "Demo", 'http://demo-social-stream.dit.upm.es/', target: '_blank' %>
                </li>
                <li class="<%= current_page?(action: 'community') && 'active' %>">
                  <%= link_to "Community", community_path %>
                </li>
                <li class="<%= current_page?(action: 'started') && 'active' %>">
                  <%= link_to "Get started", started_path %>
                </li>
              </ul>
            </div>

          </nav>              
        </div>
      </div>
    </div>
  </header> <!-- end #inner-header -->

  <div class="wrapper container-fluid">
    <div class="content_wrapper">
      <div class="content_inner_wrapper">
        <%= yield %>
      </div>
    </div>
  </div>

  <footer class="footer_wrapper">
    <div class="footer_inner_wrapper">
      <%= Time.now.year %> &copy; 
      <a href="http://www.social-stream.dit.upm.es">
        Social Stream
      </a>
      -
      <a href="http://www.dit.upm.es/">
        DIT
      </a>
      -
      <a href="http://www.etsit.upm.es/">
        ETSIT
      </a>
      -
      <a href="http://www.upm.es/">
        UPM
      </a>
    </div>
  </footer>
</body>
</html>